### Recuperar todas las newsletters
GET http://localhost:3000/newsletters
Origin: http://localhost:4200

### Recuperar una newsletter por id
GET http://localhost:3000/newsletters/DF5C24A4C56C11EF8E8774563C06B87C
Origin: http://localhost:4200

### Crear newsletter
POST http://localhost:3000/newsletters
Content-Type: application/json

{
  "email": "pepi@gmail.com"
}

### Actualizar newsletter
PUT http://localhost:3000/newsletters/DF5C24A4C56C11EF8E8774563C06B87C
Content-Type: application/json

{
  "email": "AAAA@gmail.com"
}

### Eliminar newsletter
DELETE http://localhost:3000/newsletters/DF5C24A4C56C11EF8E8774563C06B87C