### Recuperar todas las newsletters
GET http://localhost:1234/newsletters
Origin: http://localhost:4200

### Recuperar una newsletter por id
GET http://localhost:1234/newsletters/5B496CC5C49711EFAD0074563C06B87C
Origin: http://localhost:4200

### Crear newsletter
POST http://localhost:1234/newsletters
Content-Type: application/json

{
  "email": "pepi@gmail.com"
}

### Actualizar newsletter
PUT http://localhost:1234/newsletters/5B496CC5C49711EFAD0074563C06B87C
Content-Type: application/json

{
  "email": "bendicioneslapepo@gmail.com"
}

### Eliminar newsletter
DELETE http://localhost:1234/newsletters/5B496CC5C49711EFAD0074563C06B87C