name: Update production branch
on:
  push:
    branches:
      - main

jobs:
  to-produccion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Change to branch produccion
        run: |
          git fetch origin produccion
          git switch produccion
        
      - name: Push on production branch
        run: |
          git add .
          git commit -m "Update branch produccion to date: $(date +%F)"
          git push